import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Optional: set OBSIDIAN_PLUGIN_DIR to copy build output straight into a vault.
const outDir = process.env.OBSIDIAN_PLUGIN_DIR || ".";

const copyStatics = {
  name: "copy-statics",
  setup(build) {
    build.onEnd(() => {
      if (outDir === ".") return;
      fs.mkdirSync(outDir, { recursive: true });
      for (const file of ["manifest.json", "styles.css"]) {
        if (fs.existsSync(file)) {
          fs.copyFileSync(file, path.join(outDir, file));
        }
      }
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(outDir, "main.js"),
  minify: prod,
  plugins: [copyStatics],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
